### PR TITLE
Explicity set notify parameter

### PR DESCRIPTION
**Pull request by mstone121**
After upgrading to jQuery 3.3.1 and notifyjs 3.0.0, coins-notify no longer works as expected.

### CODE REVIEW

**Comment by cdaringe** [comment]
Hey Matt, did you mean to PR against the mrn code repo?

**Comment by mstone121** [comment]
I did. While I have your attention, would you mind adding me as a collaborator to the npm package?

https://www.npmjs.com/package/coins-notify

**Comment by cdaringe** [comment]
what's your handle?

**Comment by mstone121** [comment]
Same as github, mstone121.

**Pull request merged**
